nikic/php-ast

ast.c
Most extensions use `php_info_print_table_row()` instead of `php_info_print_table_header()` to show that the extension is loaded in the `phpinfo()` output. :)
This just makes the output more uniform and easier to scan.
=> Update display of extension in phpinfo()

README.md
Testing done: I checked that the rendered HTML has a working link to the github php-ast-reverter project
=> Fix rendered HTML link to php-ast-reverter

.appveyor.yml
I just took the file from the parle ext and it works with `php-ast` with a minimal change. Here are the corresponding build logs https://ci.appveyor.com/project/weltling/php-ast/history. The future adjustments should only concern the build matrix, as long as the download URLs, etc. don't change. So that's not universal, but should be ok for exts without deps. To support deps, it'll just need a further implementation, which is not the case here anyway.
Thanks.
=> AppVeyor support revamped

ast.c, php_ast.h
The `str_` members in the Zend globals structure are not initialised in request cycles that occur in different threads from the module cycle (due to the TLS storage of Zend globals). So I've shifted them out into a true global variable instead (since they are still needed in the MINIT phase).
=> Fix ZTS mode

.appveyor.yml
The build is successful so far https://ci.appveyor.com/project/weltling/php-ast/build/master.build.5 . Consequently, the build might take 3-4 minutes longer.
Thanks.
=> Update versions in the Appveyor matrix and add PHP 7.2

.appveyor.yml
The test run needs `REPORT_EXIT_STATUS` to be set, otherwise `run-tests.php` will use zero for the exit code.
=> Fix exit status propagation on AppVeyor

ast.c
The called function ast_create_virtual_node_ex is void as well.
Thanks.
=> A void function should not return

ast.c
On 32-bit, it can spare 4 bytes with teh default alignment, too.
Thanks.
=> Reduce struct size by 8 bytes on 64-bit build

.appveyor.yml
In the light of the latest issues with windows.php.net, requests with empty `User-Agent` header had to be blocked. Thus, switch to the new SDK and PS commands that send that header. The restriction should go away, once there's more bandwidth put on windows.php.net. It's requested but might take some weeks to be done.
Thanks.
=> Upgrade to latest SDK and change the way items are fetched

config.m4, config.w32
Hello,
The `$Id$` keywords were used in Subversion where they can be substituted with filename, last revision number change, last changed date, and last user who changed it.
In Git this functionality is different and can be done with Git attribute ident. These need to be defined manually for each file in the `.gitattributes` file and are afterwards replaced with 40-character hexadecimal blob object name which is based only on the particular file contents.
This patch simplifies handling of `$Id$` keywords by removing them since they are not used anymore.
Thanks for checking this out or considering merging it.
=> Remove unused Git attributes ident

ast.c, php_ast.h
The change to add typed properties makes the interpreter access cache_slot[2]
(of `AST_CACHE_SLOT_*`), which segfaults.
This fixes that.
If you see a cleaner way to do this, feel free to implement that instead
=> Fix a php 7.4-dev segfault

ast.c, tests/short_arrow_function_return.phpt
The return/parameter types would have incorrect AST nodes generated
due to the param/return type check not being added for AST_ARROW_FUNC.
Fixes #121
=> Fix generating signature types of AST_ARROW_FUNC

ast.c, tests/concat.phpt
=> Normalize representation of parenthesized concat in php 7.4

README.md, ast.c, package.xml, tests/metadata.phpt, tests/php74_ast_assign_coalesce.phpt, tests/php74_dim_alternative_syntax.phpt
=> Add DIM_ALTERNATIVE_SYNTAX flag for 7.4's $x{$i}

README.md
TysonAndre/php-parser-to-php-ast isn't actively maintained right now,
doesn't have any projects using it,
and doesn't support PHP-Parser 4.
The other polyfill has had more work done for detecting edge cases,
and handling incomplete ASTs.
- Most of the necessary functionality is already added in tolerant-php-parser 0.0.12, e.g. short echos and multi-exception catches
=> Update the link to a fallback for php-ast

README.md, package.xml, php_ast.h
Also, fix grammar nits.
(there should be commas after "Furthermore". More common choices such as
"Next,"/"Then," might be more conventional for installation instructions)
=> Update current version in docs to 70

.appveyor.yml
It may make sense to omit some combinations between 7.0 and 7.4 if this takes too long.
EDIT: https://github.com/microsoft/php-sdk-binary-tools#overview mentions that 2.1.1 should be used for php 7.0 and 7.1, but 2.2.0 is working properly in appveyor for this use case.
=> Add php 7.3 and 7.4 to appveyor tests

.appveyor.yml
It fixes: https://ci.appveyor.com/project/nikic/php-ast/builds/29843461/job/736vhys031jo5vxb#L95
=> Fixed warning in ZTS mode, as the paths are the same

README.md, package.xml, php_ast.h
We're no longer on 0.x. Removing a supported version instead of
deprecating it would be considered a backwards incompatible change by
maintainers of applications using php-ast ^1.x.
=> Update the policy for removing AST versions.

ast.c, tests/php80_noncapturing_catch.phpt
Fix a segfault, check if the ast for the variable name is not null
=> Support php 8.0 non-capturing catch

README.md, package.xml, php_ast.h
My thoughts are that 1.1.0 would be released after the php 8.0 feature freeze with any new functionality, making AST version 80 stable/current. (potentially deprecating 50-60)
EDIT: Tests also passed in php 8.0 - I guess the travis nightlies were updated.
=> Release php-ast version 1.0.7

tests/parse_code_parse_error.phpt, tests/parse_file_parse_error.phpt
Seems related to https://github.com/php/php-src/commit/55a15f32ced0bd2467e6dec0c1287a4f11b1852f#diff-ed9881373b14743d80893f15edb5675e
This is to fix  `unexpected '&'` vs `unexpected token "&"`
=> relax tests for 8.0 master

.appveyor.yml, package.xml, php_ast.h
And bump appveyor php patch versions just to run tests with a relatively up to date version of php. I don't expect the patch versions to affect test results, though
=> Release php-ast 1.0.8

ast.c
`zend_prepare_string_for_scanning` is a void (always succeed)
=> fix for 8.0.0beta3

README.md
Added the following two lines:
```
AST_NULLSAFE_METHOD_CALL: expr, method, args     // php 8.0 null safe operator
AST_NULLSAFE_PROP:        expr, prop             // php 8.0 null safe operator
```
=> README doc: add php 8.0 null safe method call and property access.

tests/zpp_errors.phpt
PHP 8 refers to arguments as "argument". This changed recently.
PHP 7 refers to arguments as "parameter".
PHP 8 travis tests should succeed in tomorrow's travis nightly build - php-src was changed today to avoid the gap that was causing php-ast to fail to parse attributes on nodes of kind AST_CLASS
=> Update zpp test expectations for php 8.

README.md, ast.c, package.xml
This will stop being experimental in 1.0.10.
Closes #178
=> Make AST version 80 the current AST version.

ast.c
This is currently harmless because 80 > 70,
but would be a potential problem if refactoring
=> Fix missing break in switch statement

tests/attributes_02.phpt
Now that php-src is providing ASTs with the expected indexes.
Fixes #187
=> Update attributes test output

.editorconfig, .travis.yml
If tests don't work with Xdebug, that's an issue with Xdebug.
(in php 8.1.0-dev, it's broken, which is normal due to rapid changes)
Seen in travis logs for #192
=> Disable Xdebug on nightly; travis does not yet support php 8.0

README.md, package.xml, php_ast.h
https://github.com/php/php-src/pull/6761 has been merged for the IS_NEVER `#define`
I will update the date before merging this
=> Release ast version 1.0.11

ast.c
(Avoid reallocating arrays, e.g. long statement lists or class lists)
=> Use array_init_size as size hint for created arrays

ast.c, package.xml, tests/php82_metadata.phpt
(But use the default deprecation behavior for ast\Metadata)
1. php-ast itself sets the dynamic property on endLineno right now,
causing deprecation notices in PHP 8.2.
Because all declaration types are associative arrays(not lists),
a future AST version number may add this as a property of
$node->children instead to avoid this notice.
2. WeakMap is only available in PHP 8.0+ (and WeakReference 7.4),
but https://github.com/phan/phan supports PHP 7.2+.
Having a Phan version (or external plugins) that can work (and be fast) with a wider range of php versions is useful for organizations trying to detect uses of undeclared properties that need to migrate.
3. Because some nodes make `$node->children` a list,
applications such as Phan using php-ast can't associate string keys
with that.
(e.g. to …
=> Allow dynamic properties (e.g. endLineno) without deprecation notice in ast\Node

.appveyor.yml, .github/workflows/main.yml, ast.c, ci/test_dockerized.sh, package.xml, php_ast.h
PHP '8.1' isn't published yet on docker hub.
Start testing with php 8.1 in appveyor
=> Update php versions tested in CI, prepare the 1.0.15 release

.github/workflows/main.yml, ast.c, tests/php82_metadata.phpt
Fix bug where ZEND_AST_ARROW_FUNC output for 'stmts' in php 8.2 did not match
earlier php versions, which would affect tools using php-ast.
Handle var_export's output changing to always be fully qualified in test
output
And start running tests in php 8.2.
=> Fix test failures seen in php 8.2

ast.c, package.xml, tests/short_arrow_function_decl_id.phpt
I noticed in 1.1.0dev that the __declId did not match a polyfill
when short arrow functions were nested.
ast_to_zval was already being called on the above lines in ast.c,
calling it again would create `ast\Node` instances again.
=> Fix redundant call to ast_to_zval

README.md
This changed to https://downloads.php.net/~windows/pecl/releases/ast/ and may change again.
https://pecl.php.net/package/ast should have the most up to date links and be easier to read.
Related to #236
=> Update the download link for php-ast

composer.json
Adds support for [PIE](https://github.com/php/pie).
Once merged, a maintainer would need to add this repo's URL to https://packagist.org/packages/submit :)
More info/documentation can be read on: https://github.com/php/pie/blob/main/docs/extension-maintainers.md
=> Add PIE support
